
import { Project, ProjectStatus, Department, TeamMember } from './types';

export const MOCK_DEPARTMENTS: Department[] = [
  { id: 'DEPT-1', name: '戰略指揮部', color: '#6366f1', manager: '總經理' },
  { id: 'DEPT-2', name: '人事行政部', color: '#64748b', manager: '行政主管' },
  { id: 'DEPT-3', name: '財務部', color: '#0284c7', manager: '財務主管' },
  { id: 'DEPT-4', name: '生活品質 第一工程部', color: '#16a34a', manager: '工務主管' },
  { id: 'DEPT-5', name: '品質管理部', color: '#8b5cf6', manager: '品管主管' },
  { id: 'DEPT-6', name: '業務部', color: '#ea580c', manager: '業務經理' },
  { id: 'DEPT-7', name: '行銷部', color: '#ec4899', manager: '行銷經理' },
  { id: 'DEPT-8', name: '傑凱工程 第三工程部', color: '#0ea5e9', manager: '工務主管' },
  { id: 'DEPT-9', name: '琥凱爾工程 第四工程部', color: '#a855f7', manager: '工務主管' }
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'BNI2024001',
    departmentId: 'DEPT-6',
    name: '桃園至善街290號防水工程',
    category: '防水工程',
    source: 'BNI',
    client: '冠亨商設計',
    referrer: '舊客介紹',
    manager: '陳信寬',
    startDate: '2024-01-05',
    endDate: '2024-03-05',
    createdDate: '2024-01-05',
    budget: 0,
    spent: 0,
    progress: 0,
    status: ProjectStatus.COMPLETED,
    tasks: [],
    phases: [],
    financials: { labor: 40, material: 30, subcontractor: 20, other: 10 }
  },
  {
    id: 'BNI2025002',
    departmentId: 'DEPT-6',
    name: '桃園龜山民安街11號防水工程',
    category: '防水工程',
    source: 'BNI',
    client: '璇凱伯修',
    referrer: '網站預約',
    manager: '陳文凱',
    startDate: '2025-01-05',
    endDate: '2025-03-10',
    createdDate: '2025-01-05',
    budget: 0,
    spent: 0,
    progress: 0,
    status: ProjectStatus.COMPLETED,
    tasks: [],
    phases: [],
    financials: { labor: 40, material: 30, subcontractor: 20, other: 10 }
  },
  {
    id: 'JW2601003',
    departmentId: 'DEPT-6',
    name: '樹林區三龍街24巷16號國為海砂屋補強工程',
    category: '補強工程',
    source: 'JW',
    client: '邱金龍',
    referrer: '',
    manager: '余家豪',
    startDate: '2026-01-05',
    endDate: '2026-04-15',
    createdDate: '2026-01-05',
    budget: 0,
    spent: 0,
    progress: 0,
    status: ProjectStatus.NEGOTIATING,
    tasks: [],
    phases: [],
    financials: { labor: 40, material: 30, subcontractor: 20, other: 10 }
  },
  {
    id: 'BNI2601004',
    departmentId: 'DEPT-6',
    name: '光復北路190巷40號章省予大樓管線修復工程',
    category: '水電機電',
    source: 'BNI',
    client: '章省予',
    referrer: '',
    manager: '余家豪',
    startDate: '2026-01-05',
    endDate: '',
    createdDate: '2026-01-05',
    budget: 0,
    spent: 0,
    progress: 0,
    status: ProjectStatus.NEGOTIATING,
    tasks: [],
    phases: [],
    financials: { labor: 40, material: 30, subcontractor: 20, other: 10 }
  },
  {
    id: 'OC2601005',
    departmentId: 'DEPT-6',
    name: '光復南路住宅電力系統更新工程',
    category: '水電機電',
    source: '網路客',
    client: '光復南路業主',
    referrer: '',
    manager: '郭俊宏',
    startDate: '2026-01-05',
    endDate: '',
    createdDate: '2026-01-05',
    budget: 0,
    spent: 0,
    progress: 0,
    status: ProjectStatus.NEGOTIATING,
    tasks: [],
    phases: [],
    financials: { labor: 40, material: 30, subcontractor: 20, other: 10 }
  },
  {
    id: 'CORP2601002',
    departmentId: 'DEPT-6',
    name: '台中商業辦公室擴建',
    category: '室內裝修',
    source: '企業',
    client: '科技公司',
    referrer: '舊客介紹',
    manager: '林靜宜',
    startDate: '2026-02-15',
    endDate: '2026-08-20',
    createdDate: '2026-01-20',
    budget: 8800000,
    spent: 2100000,
    progress: 15,
    status: ProjectStatus.CONSTRUCTING,
    tasks: [],
    phases: [],
    financials: { labor: 25, material: 55, subcontractor: 15, other: 5 }
  }
];

export const MOCK_TEAM_MEMBERS: TeamMember[] = [];
